server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: Better-Register
  security:
    user:
      name: better
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: better
        password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS