server:
  port: 8301
spring:
  application:
    name: Better-Gateway
  boot:
    admin:
      client:
        url: http://${better-monitor-admin}:8401
        username: better
        password: 123456
  cloud:
    gateway:
      routes:
        - id: Better-Auth
          uri: lb://Better-Auth
          predicates:
            - Path=/auth/**
        - id: Better-Server-UPMS
          uri: lb://Better-Server-UPMS
          predicates:
            - Path=/upms/**
        - id: Better-Server-test
          uri: lb://Better-Server-Test
          predicates:
            - Path=/test/**
      default-filters:
        - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://better:123456@${better-register}:8001/register/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway